const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',

    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',

    //user
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
    PROCESS_LOGOUT: 'PROCESS_LOGOUT',
    CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',

    //admin
    FETCH_GENDER_START: 'FETCH_GENDER_START',
    FETCH_GENDER_SUCCEED: 'FETCH_GENDER_SUCCEED',
    FETCH_GENDER_FAILED: 'FETCH_GENDER_FAILED',
    //role
    FETCH_ROLE_SUCCEED: 'FETCH_ROLE_SUCCEED',
    FETCH_ROLE_FAILED: 'FETCH_ROLE_FAILED',
    //position
    FETCH_POSITION_SUCCEED: 'FETCH_POSITION_SUCCEED',
    FETCH_POSITION_FAILED: 'FETCH_POSITION_FAILED',
    //save user
    CREATE_USER_SUCCEED: 'CREATE_USER_SUCCEED',
    CREATE_USER_FAILED: 'CREATE_USER_FAILED',
    
    //delete user
    DELETE_USER_SUCCEED: 'DELETE_USER_SUCCEED',
    DELETE_USER_FAILED: 'DELETE_USER_FAILED',
    
    //edit user
    EDIT_USER_SUCCEED: 'EDIT_USER_SUCCEED',
    EDIT_USER_FAILED: 'EDIT_USER_FAILED',

     //get all user
    FETCH_ALL_USERS_SUCCEED: 'FETCH_ALL_USERS_SUCCEED',
    FETCH_ALL_USERS_FAILED: 'FETCH_ALL_USERS_FAILED',

     //top doctor
    FETCH_TOP_DOCTORS_SUCCEED: 'FETCH_TOP_DOCTORS_SUCCEED',
    FETCH_TOP_DOCTORS_FAILED: 'FETCH_TOP_DOCTORS_FAILED', 
    
    //get all doctors
    FETCH_ALL_DOCTORS_SUCCEED: 'FETCH_ALL_DOCTORS_SUCCEED',
    FETCH_ALL_DOCTORS_FAILED: 'FETCH_ALL_DOCTORS_FAILED', 
    
    //save info doctor
    SAVE_INFO_DOCTOR_SUCCEED: 'SAVE_INFO_DOCTOR_SUCCEED',
    SAVE_INFO_DOCTOR_FAILED: 'SAVE_INFO_DOCTOR_FAILED',

    //get all code
    FETCH_ALL_CODE_SCHEDULE_HOURS_SUCCEED: 'FETCH_ALL_CODE_SCHEDULE_HOURS_SUCCEED',
    FETCH_ALL_CODE_SCHEDULE_HOURS_FAILED: 'FETCH_ALL_CODE_SCHEDULE_HOURS_FAILED', 
    
    //doctor price
    FETCH_REQUIRED_DOCTOR_INFO_START: 'FETCH_REQUIRED_DOCTOR_INFO_START',
    FETCH_REQUIRED_DOCTOR_INFO_SUCCEED: 'FETCH_REQUIRED_DOCTOR_INFO_SUCCEED',
    FETCH_REQUIRED_DOCTOR_INFO_FAILED: 'FETCH_REQUIRED_DOCTOR_INFO_FAILED',
})

export default actionTypes;